# For test execution

# Machine (Win/Mac/Linux)

# Software to be installed (Node.js)

# Need to execute the test
############################################

name: 02_Select_Browser.

# Events
on:
  # Manual trigger
  workflow_dispatch:
    inputs:
      browser:
        description: 'Select browser (CHROME | EDGE | ELECTRON | FIREFOX)'
        options:
          - 'CHROME'
          - 'EDGE'
          - 'ELECTRON'
          - 'FIREFOX'
        required: true
        default: 'CHROME'
        type: choice

jobs:
  ui_test_browser_selected:
    runs-on: ubuntu-latest

    steps:
      # Checking out the code from Github repository to the machine (ubuntu-latest)
      - name: Checkout code
        uses: actions/checkout@v4

      # Installing Node JS
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16
      
      # Installing dependencies required for Cypress
      - name: Install dependencies
        run: npm ci

      - name: Run Cypress UI tests
        run: npm run cy:test:${{ github.event.inputs.browser }}
        
      # Upload test reports as artifact on GitHub
      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: UI Tests report - ${{ github.event.inputs.browser }}
          path: cypress/reports