# For test execution

# Machine (Win/Mac/Linux)

# Software to be installed (Node.js)

# Need to execute the test
############################################

name: 03_Run in all browsers.

# Events
on:
  # Manual trigger
  workflow_dispatch:

jobs:
  ui_test_all_browsers:
    runs-on: ubuntu-latest
    #Add strategy Matrix for run in paralell.
    strategy:
      matrix:
        browser: ['CHROME', 'EDGE', 'ELECTRON', 'FIREFOX']

    steps:
      # Step 1: Checking out the code from GitHub repo to the machine (ubuntu-latest)
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Installing Node.js
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      # Step 3: Installing dependencies for Cypress
      - name: Install dependencies for Cypress
        run: npm ci

      # Step 4: Run Cypress test on the selected browser
      - name: Run Cypress UI tests
        run: npm run cy:test:${{ matrix.browser }}

      # Step 5: Upload test reports as artifact on GitHub
      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: UI Tests report - ${{ matrix.browser }} - ${{ github.run_id }}
          path: cypress/reports