# For test execution

# Machine (Win/Mac/Linux)

# Software to be installed (Node.js)

# Need to execute the test
############################################

name: 03_Run in all browsers.

# Events
on:
  # Manual trigger
  workflow_dispatch:

jobs:
  ui_test_chrome:
    runs-on: ubuntu-latest

    #Add Strategy: Use matrix strategy for run in paralell test execution in diferent browsers.
    strategy:
      matrix:
        browser: [CHROME, FIREFOX, ELECTRON, EDGE]

    steps:
      # Step 2: Checking out the code from the GitHub repository to the machine (ubuntu-latest)
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 3: Installing Node.js
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16
      
      # Step 4: Installing dependencies required for Cypress
      - name: Install dependencies
        run: npm ci

      # Step 5: Run Cypress tests on all supported browsers from the matrix
      - name: Run Cypress UI tests
        run: npm run cy:tests:${{ matrix.browser }}
        
      # Step 6: Upload test reports as artifacts
      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: UI Tests Report
          path: cypress/reports